### ISSUE TITLE
Failed to create GPU from string "0:0"

### ISSUE THREAD

**Issue by Balttazarr** [JeanOUINA/VPoW#1]
Hello all,

 as mentioned in the title .. my old 650m with 425.31 drivers won't run the vpow node. 

 Below a screenshot of the error:
 
![error101](https://user-images.githubusercontent.com/26445216/159343760-cee4487b-f8c3-40cf-a9f2-0759e77da11a.png)

**Comment by JeanOUINA** [comment]
Try to update your drivers
